# Generated by Django 4.2.16 on 2026-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='choices',
            field=models.CharField(choices=[('web_development', 'Web Development'), ('api_development', 'API Development'), ('database_design', 'Database Design'), ('consultation', 'Consultation'), ('other', 'Other')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
