# Generated by Django 4.2.16 on 2026-01-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_message_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='choices',
            new_name='project_type',
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
